{{- define "globalping-probe.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "globalping-probe.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "globalping-probe.labels" . | nindent 4 }}
type: Opaque
stringData:
  gp-adoption-token: {{ .Values.globalpingToken | quote }}
{{- end }}
{{- if .Values.globalpingToken }}
{{- include "globalping-probe.secret" . }}
{{- end }}
