{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "globalping-probe.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "globalping-probe.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "globalping-probe.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  {{- with .Values.networkPolicy.egress }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

